POST http://localhost:5000/signup
Content-Type: application/json

{
    "nomEtudiant" : "Eren",
    "prenomEtudiant" : "Jäger",
    "mailEtudiant" : "eren@test.com",
    "mdpEtudiant" : "eren",
    "anneePromo" : "IG3"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "mailEtudiant" : "armin@test.com",
    "mdpEtudiant" : "armin"
}