POST http://localhost:5000/signup
Content-Type: application/json

{
    "nomEtudiant" : "Laget",
    "prenomEtudiant" : "Axel",
    "mailEtudiant" : "axel@test.com",
    "mdpEtudiant" : "axel",
    "anneePromo" : "IG3"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "mailEtudiant" : "armin@test.com",
    "mdpEtudiant" : "armin"
}

###
GET http://localhost:5000/evenements/admin_all_events
###
GET http://localhost:5000/evenements/admin_view_event/5fde26d71239673a9cfab8cd
